# Generated by Django 5.2 on 2025-05-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_supportticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="blockList",
        ),
    ]
