# Generated by Django 5.2 on 2025-06-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_delete_blocklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datalimit",
            name="value",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="filelimit",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
