# Generated by Django 5.2 on 2025-06-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_delete_blocklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirebaseDataLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Limit danych",
                "verbose_name_plural": "Limit danych",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FirebaseFileLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Limit plików",
                "verbose_name_plural": "Limit plików",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="dataLimit",
        ),
        migrations.DeleteModel(
            name="fileLimit",
        ),
    ]
